version: "3.7"

services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    env_file:
      - db.env
    ports:
      - 3306:3306

  test_db:
    image: mysql:5.7
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - db.test.env
    ports:
      - 3307:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  api:
    build: ${PWD}/api/.
    ports:
      - 3080:3080
    volumes:
      - ./api:/usr/src/app/api
      - images:/usr/src/app/api/public
    depends_on:
      - db
      - test_db

  frontend:
    build: ${PWD}/frontend/.
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/frontend

volumes:
  db-volume:
  images:
