import React from 'react';
import Head from 'next/head';
import styled from 'styled-components';

import { Header } from './header/Header';
import { Footer } from './Footer';
import { spacing, widths } from '@variables';
interface Props {
  title: string;
}

export const Layout: React.FC<Props> = ({ title, children }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        {/* Montserrat font family */}
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,200;0,400;0,700;1,200;1,400;1,700&display=swap"
          rel="stylesheet"
        />

        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
          integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </Head>
      <>
        <Header />
        <ContentLayout>
          <main>{children}</main>
          <Footer />
        </ContentLayout>
      </>
    </>
  );
};

// be aware of the min-height that might change on mobile
const ContentLayout = styled.div`
  display: flex;
  flex-direction: column;
  min-height: calc(100vh - 90px);
  justify-content: space-between;
  main {
    width: ${widths.lg};
    margin: ${spacing.lg} auto;
  }
`;
