import React from 'react';
import Head from 'next/head';
import { Header } from '../header/Header';
import { StyledLayout } from './StyledLayout';
interface Props {
  title: string;
}

export const Layout: React.FC<Props> = ({ title, children }) => {
  return (
    <StyledLayout>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css?family=Quicksand:300,500" rel="stylesheet" />
      </Head>
      <Header />
      <main>{children}</main>
    </StyledLayout>
  );
};
